### ISSUE TITLE
Call to protected method Consilience\Flysystem\Azure\AzureFileAdapter::getUrl() from context 'Illuminate\Filesystem\FilesystemAdapter' 

### ISSUE THREAD

**Issue by emtiazzahid** [academe/laravel-azure-file-storage-driver#1]
When i tried to get the image in blade with url, its showing `Call to protected method Consilience\Flysystem\Azure\AzureFileAdapter::getUrl() from context 'Illuminate\Filesystem\FilesystemAdapter' `

in blade i write image src like this : 
 ` <img src="{{ \Storage::disk('azure')->url('public/uploads/mailbox/1/cbdf041a-6e01-42f0-868f-91bfccdae2bc.png') }}" alt="Azure Image">`

Can you please help me to get over this.

**Comment by judgej** [comment]
If you make the method public, does this work? Could you post or send me an example URL.

The assumption on my part is that these URLs require authentication to use, so would not be any use outside the context of the flysystem. But if some of these URLs can be accessed publicly, then it makes sense if the URLs are available to the application too.

**Comment by emtiazzahid** [comment]
yes it works when i changed it from protected to public.

**Comment by judgej** [comment]
Do you have an example path you could give me, or any details on what needs to be set up to make the paths public? I just get a "invalid headers" error when I try to access a path, due to lack of authentication.

**Comment by judgej** [comment]
It's the URL the desktop app provides, so I'll just make it a public method.

**Comment by judgej** [comment]
Try updating the package and its dependencies. `getUrl()` should now be public.

**Comment by InvokerMaster** [comment]
Hello.
Can you explain how to get stream from Azure File Storage?
Just noticed that there is a function called readStream.

**Comment by judgej** [comment]
This is the general documentation for flysystem streams:

https://flysystem.thephpleague.com/docs/usage/filesystem-api/#using-streams-for-reads-and-writes

Laravel exposes the full flysystem driver, so you should be able to access the stream reader directly. It is not an area I have tested extensively at this stage, but should work.

**Comment by judgej** [comment]
@emtiazzahid did you get a chance to try out the updated flysystem driver? I'll close this issue, but feel free to follow it up on the underlying driver package if you are still having problems here: https://github.com/academe/flysystem-azure-file-storage/issues/3

**Comment by InvokerMaster** [comment]
Thank you for your reply.
Well actually I get stream data to show video from Azure file storage.
And I just wanted to make sure that the stream methods on flysystem in Laravel 
also works for this repo.

**Comment by InvokerMaster** [comment]
If it's possible then Thank you very much

**Comment by judgej** [comment]
Give it a go, and let me know on https://github.com/academe/flysystem-azure-file-storage/issues if it does not.

**Comment by InvokerMaster** [comment]
Okay.
Thank you
